---

- name: Check Disk Usage
  hosts: all
  connection: ansible.netcommon.network_cli
  gather_facts: false
  vars:
        limit_max: "1"
  tasks:
   - name: Checking Disk on your Server
     shell: df -hBG "/" | tail -n 1 | awk {'print $4 '}  | sed 's/G//g'
     register: disk

   - name: Checking Disk on your Server
     shell: df -h "/" | tail -n 1 | awk {'print $5 '}  | sed 's/%//g'
     register: use

   - name: Server List
     shell: echo "{{ inventory_hostname }}" | awk '{ print $1 }' | cut -d "." -f1
#     shell: echo "{{ inventory_hostname }}"
     register: server

#   - name: Show debugging on your fucking terminal
#     debug:
#       msg:
#         - "{{ disk.stdout }}"
#         - "{{ use.stdout }}"
#         - "{{ server.stdout }}"

   - name: Adding record disk usage to list on file
     lineinfile:
      dest: avail_disk.txt
      line: "{{ mountpoint }} reache {{ use.stdout }}%, remaining disk : {{ disk.stdout }} GB ON {{ server.stdout }} !"
      state: present
     delegate_to: 127.0.0.1
     register: msgtxt
     with_items:
       - "{{ disk.stdout }}"
       - "{{ server.stdout }}"
       - "{{ use.stdout }}"
     when: use.stdout >= limit_max #minimum % disk usage want add to list
